pipeline {
  agent any
  stages {
    stage('Linting') {
	  agent {
        docker {
            image 'hadolint/hadolint:latest-ubuntu'
        }
      }
      steps {
        sh 'hadolint Dockerfile | tee -a hadolint_lint.txt'
        }
     }
    stage('Build image') {
      steps{
        sh 'docker build --tag=green .'
      }
    }
	stage(Push image') {
	  steps{
	    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD']]){  
		sh '''
          docker push hatwithpins/green
		'''
	   }
	  }
	}
	stage('Set current kubectl context') {
	  steps{
	    sh 'kubectl config use-context arn:aws:eks:us-west-2:'
	  }
	}
	stage('Deploy container') {
	 steps{
	   sh 'kubectl apply -f ./green-controller.json'
	 }
   }
}