pipeline {
  agent any
  stages {
    stage('Linting') {
	  agent {
        docker {
            image 'hadolint/hadolint'
        }
      }
      steps {
	      
	      dir('/var/lib/jenkins/workspace/Capstone@2/Capstone/Green'){
        	sh 'hadolint Dockerfile'
	      }
	      dir('/var/lib/jenkins/workspace/Capstone@2/Capstone/Blue'){
		sh 'hadolint Dockerfile'
	      }
        }
     }
    stage('Build blue') {
      steps{
	      dir('/var/lib/jenkins/workspace/Capstone@2/Capstone/Blue'){
        	sh 'docker build --tag=blue .'
	      }
      }
    }
	stage('Push blue') {
	  steps{
	    withCredentials([usernamePassword( credentialsId: 'dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]){  
		sh 'pip3 install --upgrade --user awscli'
		sh 'docker login -u $USERNAME -p $PASSWORD'
	  	sh 'docker tag blue hatwithpins/blue:latest'
          	sh 'docker push hatwithpins/blue:latest'  
	   }
	  }
	}
	stage('Set current kubectl context') {
	  steps{
            sh 'aws eks update-kubeconfig --name Udacity'
	    sh 'kubectl config use-context arn:aws:eks:us-west-2:013193330021:cluster/Udacity'
	  }
	}
	stage('Deploy blue container') {
	 steps{
	   sh 'kubectl apply -f ./blue-controller.json'
	 }
   }
   stage('Build green') {
      steps{
	      dir('/var/lib/jenkins/workspace/Capstone@2/Capstone/Green'){
        	sh 'docker build --tag=green .'
	      }
      }
    }
	stage('Push green') {
	  steps{
	    withCredentials([usernamePassword( credentialsId: 'dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]){  
		sh 'docker login -u $USERNAME -p $PASSWORD'
	  	sh 'docker tag blue hatwithpins/green:latest'
          	sh 'docker push hatwithpins/green:latest'  
	   }
	  }
	}
	stage('Deploy green container') {
	 steps{
	   sh 'kubectl apply -f ./green-controller.json'
	 }
   }
    stage('Deploy load balancer') {
	  steps{
		  dir('/var/lib/jenkins/workspace/Capstone@2/Capstone/'){
	    		sh 'kubectl apply -f ./blue-green-service.json'
		  }
	  }
	}
}
}
